### ISSUE TITLE
npm postinstall script on Windows

### ISSUE THREAD

**Issue by hastebrot** [Polymer/web-component-tester#116]
Hi! I've executed `npm install -g web-component-tester` (Windows 7, iojs 1.0.4, npm 2.3.0; each 64-bit).

It fails with:

~~~
-----
selenium-standalone installation finished
-----
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\iojs\\\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "web-component-tester"
npm ERR! node v1.0.4
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! wct-sauce@1.0.1 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wct-sauce@1.0.1 postinstall script 'node scripts/postinstall.js'.
~~~

Strangely `npm install wct-sauce` succeeds (including the post install script).

**Comment by hastebrot** [comment]
With node v0.10.36 and npm v1.4.28 it very quickly fails. `"Failed at the sauce-connect-launcher@0.9.3 postinstall script."`

**Comment by nevir** [comment]
Are you able to install `wct-sauce` on its own?

**Comment by nevir** [comment]
This is really strange; you're not the only one hitting this too...

**Comment by nevir** [comment]
Can you try a `npm cache clean` followed by another try at installing it?

**Comment by hastebrot** [comment]
Yes, `npm install wct-sauce` gave no errors. Interestingly, I ran `npm install wct-local` and then `npm install -g web-component-tester` and npm downloaded and executed post-install for wct-local a second time.

Will try `npm cache clean`.

**Comment by nevir** [comment]
both plugins have a postinstall script, which may be confusing matters here - `wct-local` (selenium-standalone) and `wct-sauce` (sauce-connect-launcher)

**Comment by hastebrot** [comment]
Well, I installed `wct-local` to shorten installation time. Didn't work.

**Comment by nevir** [comment]
Hmm. Can you try a non-global install of web-component-tester (say into a temp directory)?

**Comment by hastebrot** [comment]
Non-global install worked.

**Comment by nevir** [comment]
Lovely. Ok hm.

```sh
npm uninstall -g sauce-connect-launcher selenium-standalone launchpad wct-local wct-remote web-component-tester 
npm install -g web-component-tester
```

**Comment by hastebrot** [comment]
I get the error again.

**Comment by nevir** [comment]
Can you post the full log from that failure?

**Comment by hastebrot** [comment]
https://gist.github.com/hastebrot/e6286ca66dc5ccae01c0

**Comment by nevir** [comment]
Ok, I just published `wct-sauce@1.0.2` w/ some additional logging, and yanked `1.0.1` - mind trying to install again?

Ideally the output starts with something like:

```sh
> wct-sauce@1.0.1 postinstall /Users/imac/work/projects/wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Creating directory: /Users/imac/work/projects/wct-sauce/node_modules/sauce-connect-launcher/sc
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
```

**Comment by hastebrot** [comment]
I ran

~~~
npm cache clear
npm install -g web-component-tester
~~~

It worked. A difference is, that it first ran post install for wct-sauce and then post install for wct-local.

Here a part from the console output:

~~~
> sauce-connect-launcher@0.9.3 postinstall C:\Users\benjamin\AppData\Roaming\npm
\node_modules\web-component-tester\node_modules\wct-sauce\node_modules\sauce-con
nect-launcher
> node scripts/install.js

-
> wct-sauce@1.0.2 postinstall C:\Users\benjamin\AppData\Roaming\npm\node_modules
\web-component-tester\node_modules\wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Creating directory: C:\Users\benjamin\AppData\Roaming\npm\node_modules\web-compo
nent-tester\node_modules\wct-sauce\node_modules\sauce-connect-launcher\sc
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 3.18MB
Unzipping sc-4.3.5-win32.zip
Removing sc-4.3.5-win32.zip
Sauce Connect downloaded correctly
Removing C:\Users\benjamin\AppData\Roaming\npm\node_modules\web-component-tester
\node_modules\wct-sauce\node_modules\sauce-connect-launcher\sc\sc-4.3.5-win32.zi
p

> wct-local@1.0.1 postinstall C:\Users\benjamin\AppData\Roaming\npm\node_modules
\web-component-tester\node_modules\wct-local
> node scripts/postinstall.js

----------
selenium-standalone installation starting
----------
~~~

**Comment by dominik0711** [comment]
We have a same kind of problem on our Codeship CI:
Platform (Linux VMware)
node 0.10.25

```
> sauce-connect-launcher@0.9.3 postinstall /home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher
> node scripts/install.js   
> wct-sauce@1.0.2 postinstall /home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/wct-sauce > node scripts/postinstall.js  
-e/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/lodash/dist/lodash.js:6256 
source += "' +\n__e(" + escapeValue + ")  
^^^ SyntaxError: Unexpected token ILLEGAL 
at Module._compile (module.js:439:25) 
at Object.Module._extensions..js (module.js:474:10) 
at Module.load (module.js:356:32) 
at Function.Module._load (module.js:312:12) 
at Module.require (module.js:364:17) 
at require (module.js:380:17) 
at Object.<anonymous> (/home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:6:7) 
at Module._compile (module.js:456:26) 
at Object.Module._extensions..js (module.js:474:10) 
at Module.load (module.js:356:32)  
> ws@0.5.0 install /home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws 
> (node-gyp rebuild 2> builderror.log) || (exit 0)  

-ake: Entering directory `/home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build' 
CXX(target) Release/obj.target/bufferutil/src/bufferutil.o 
/ake: Leaving directory `/home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'  

> ws@0.4.31 install /home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws 
> (node-gyp rebuild 2> builderror.log) || (exit 0)  
/ake: Entering directory `/home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build' 
CXX(target) Release/obj.target/bufferutil/src/bufferutil.o SOLINK_MODULE(target) Release/obj.target/bufferutil.node 
-ake: Leaving directory `/home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'  

> wct-local@1.0.1 postinstall /home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/wct-local 
> node scripts/postinstall.js  
--standalone installation starting 
----------
--- 
selenium install: 
from: http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar 
to: /home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/2.44.0-server.jar 
--- 
chrome install: 
from: http://chromedriver.storage.googleapis.com/2.13/chromedriver_linux64.zip 
to: /home/rof/src/bitbucket.org/artificialunit/arcwork/build/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.13-x64-chromedriver 
--
standalone installation finished 
-----

npm ERR! Linux 3.13.0-35-generic 
npm ERR! argv "node" "/home/rof/.nvm/v0.10.25/bin/npm" "install" 
npm ERR! node v0.10.25 
npm ERR! npm v2.3.0 
npm ERR! code ELIFECYCLE  
npm ERR! wct-sauce@1.0.2 postinstall: `node scripts/postinstall.js` 
npm ERR! Exit status 8 
npm ERR!  
npm ERR! Failed at the wct-sauce@1.0.2 postinstall script 'node scripts/postinstall.js'. 
npm ERR! This is most likely a problem with the wct-sauce package, 
npm ERR! not with npm itself. 
npm ERR! Tell the author that this fails on your system: 
npm ERR! node scripts/postinstall.js npm ERR! You can get their info via: 
npm ERR! npm owner ls wct-sauce npm ERR! There is likely additional logging output above.  
npm ERR! Please include the following file with any support request: 
npm ERR! /home/rof/src/bitbucket.org/artificialunit/arcwork/build/npm-debug.log
```

**Comment by nevir** [comment]
Agh, @dominik0711 looks like [the npm bug](https://github.com/npm/npm/issues/6624) is back to being triggered; I'll whip up a workaround.

In the meantime installing WCT and lodash at the same time should alleviate it (e.g. `npm install lodash web-component-tester`)

**Comment by dominik0711** [comment]
@nevir. To install lodash web-component-tester together is quit difficult, because all packages will be installed through package.json and I don't know if lodash and web-component-tester can be installed together. Or is there a way to do that with package.json?

**Comment by nevir** [comment]
I _think_ that if you depend on lodash and WCT in your `package.json`, it should work. Or, if you can run multiple commands; just install lodash first

The main issue is that npm is running the postinstall script before it has finished copying lodash into place

**Comment by dominik0711** [comment]
So, I have added a command to install lodash before the installation process through package.json. Still the same error, see log:

![ci_log](https://cloud.githubusercontent.com/assets/1011188/5964041/5a67fd34-a7f1-11e4-9e24-00d31d3d4ddd.png)

**Comment by dominik0711** [comment]
So, installing lodash version `2.4.1` before all other packages from package.json seems to satisfy the npm install process of web-components-tester.
Nevertheless upgrading to web-components-tester from `2.0.5` to `2.1.3` is breaking the API! Could you please, please follow the rules **NOT** to change the API in minor but only in major versions?!
Versions > 2.0.5 have now other API in config.js.

`browsers` has changed to `activeBrowsers` and our setting are no longer valid. Could you please tell me the right syntax for our "old fashion settings":
```
browsers : [{ browserName: 'chrome',
chromeOptions: { excludeSwitches : ['ignore-certificate-errors'] }}],
```
Thanks in advance!

**Comment by nevir** [comment]
Old style browsers should continue to work! Wasn't my intention to be
backwards incompatible :( I'll dig into that

What is occurring with that config for you?

**Comment by dominik0711** [comment]
I'll get the following output:

```
The --browsers flag/option is deprecated. Please use --local and --sauce instead.
Warning: Object #<Object> has no method 'indexOf' Use --force to continue.
```

We are running our wct test through grunt. With `--force` the tests did not run either. Any suggestions?

**Comment by nevir** [comment]
@dominik0711 I've got a fix for that in 783b5579f3f95a83d799c1ce0ee1c0afd0c7ea18 - I'll have it out next version

**Comment by nevir** [comment]
Ok, I've got exponential backoff on the requires in both plugins (https://github.com/Polymer/wct-sauce/commit/c840bb2d2e1a1042fee73c31260f2319f73cee5b and https://github.com/Polymer/wct-local/commit/7f8e1b0659ada849afec5464f4f16ac852d734eb). Hopefully counters that bug.

**Comment by JesterXL** [comment]
Getting this with Node 4. Going to try to go back to 0.12 and see if it happens.

**Comment by JesterXL** [comment]
Meh:

```javascript
Failed to load plugin "local": SyntaxError: /Users/jessewarden/Documents/_Projects/Starting-Strength-Polymer/node_modules/restify/node_modules/bunyan/lib/bunyan.js:876
});
 ^
Unexpected token )
```

**Comment by JesterXL** [comment]
Should I go back to Node 0.10?

**Comment by JesterXL** [comment]
Blah, same in 0.10:

```javascript
/Users<my project path>/node_modules/restify/node_modules/bunyan/lib/bunyan.js:876
});
 ^

Failed to load plugin "local": SyntaxError: Unexpected token )

**Comment by JesterXL** [comment]
Disregard, nuked node_modules and bower_components, re-ran npm install && bower install, and all is (mostly) well.
