### ISSUE TITLE
Fail to install behind a corporate proxy.

### ISSUE THREAD

**Issue by jmorille** [Polymer/web-component-tester#140]
Behind the a corporate proxy the npm install of web-component-tester fail.
The cause is wtc-saucer installation fail in post-installtion script with a direct http.request cf https://github.com/Polymer/wct-sauce/issues/5#issuecomment-78175279.

This dependency is needed as mandatory ? could be an optional dependency ?

cf the error installation
``` shell
user@host:/tmp$ npm install web-component-tester
 
> ws@0.5.0 install /tmp/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/tmp/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/tmp/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
 
> sauce-connect-launcher@0.9.3 postinstall /tmp/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher
> node scripts/install.js

 
> ws@0.4.31 install /tmp/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/tmp/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/tmp/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'

> wct-local@1.3.1 postinstall /tmp/node_modules/web-component-tester/node_modules/wct-local
> node scripts/postinstall.js

----------
selenium-standalone installation starting
----------

---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
to: /tmp/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/2.45.0-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.14/chromedriver_linux64.zip
to: /tmp/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.14-x64-chromedriver


-----
selenium-standalone installation finished
-----

> wct-sauce@1.2.0 postinstall /tmp/node_modules/web-component-tester/node_modules/wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

npm ERR! wct-sauce@1.2.0 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the wct-sauce@1.2.0 postinstall script.
npm ERR! This is most likely a problem with the wct-sauce package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls wct-sauce
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/home/a000cqp/opt/nodejs/bin/node" "/home/a000cqp/opt/nodejs/bin/npm" "install" "web-component-tester"
npm ERR! cwd /tmp
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

````

**Comment by nevir** [comment]
I'd definitely like to make wct-sauce an optional dependency for WCT 3.0 - but don't want to drop it just yet for fear of breaking existing users

**Comment by jmorille** [comment]
But you block some new users to use it :
 - All Users that work in big company that could not use it if they are behind a corporate firewall
 - And in some company that have  Business Continuity Plan (BCP) constraint, and in which one that the development environment should installable even if a no internet connectivity.

Do you have a plan for the release of the WCT 3.0 ?

**Comment by nevir** [comment]
Soon!

`wct-local` and `wct-sauce` are now optional dependencies on master

**Comment by jmorille** [comment]
The new user, thank you !!!

**Comment by sonnyking** [comment]
Install still fails for my team behind the corp proxy. I see that act-sauce is an optional deep but I still get error: "Could not find WCT plugin named "sauce""

**Comment by jonniespratley** [comment]
+1

**Comment by DevVex** [comment]
+1

**Comment by HenriTEL** [comment]
I don't know exactly why but when I initialize an element using `polymer init` from my Polymer Starter Kit clone i get `error: "Could not find WCT plugin named "sauce""`
But when I initialize it outside everything is going well.

I guess it's because the polymer init script detect a `bower` installation and assume that all packages are already installed, `sauce` in particular .

**Comment by benmak11** [comment]
+1

**Comment by Sue1024** [comment]
+1

**Comment by Sue1024** [comment]
+1

**Comment by BigZolo** [comment]
👍

**Comment by joelgenter** [comment]
+1

**Comment by digeomel** [comment]
+1
