### ISSUE TITLE
WCT execution yields error

### ISSUE THREAD

**Issue by yelurinaveen** [Polymer/web-component-tester#144]
No test suites were found matching your configuration

**Comment by nevir** [comment]
It says that when it can't find any files on disk matching your configuration. I'll add some extra detail to that error to hopefully aid debugging (the paths it searched).

By default it is looking for `.js` or `.html` files under `test/`

**Comment by nevir** [comment]
I'll have a better error out next version; and in the meantime, feel free to post the command you used to run WCT, as well as the configuration you used and I can help debug

**Comment by m3os** [comment]
Same Problem Here : 
--------------------------------------------------------------------

root@server:~# polymer test

Error: No test suites were found matching your configuration

  WCT searched for .js and .html files matching: test/

  Relative paths were resolved against: /root

error: [cli.main]   cli runtime exception: Error: No test suites were found matching your configuration

  WCT searched for .js and .html files matching: test/

  Relative paths were resolved against: /root
error: [cli.main]   Error: No test suites were found matching your configuration

  WCT searched for .js and .html files matching: test/

  Relative paths were resolved against: /root
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/config.js:560:19)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/config.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/config.js:16:12)
    at Object.validate (/usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/config.js:543:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:64:22)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:4:58)
    at <anonymous>
