### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by MrAntix** [Polymer/web-component-tester#214]
Hi I get errors trying to install on windows

I am running windows 10 and VS2015 14.0.23107.0 D14REL
in Admin cmd window

    > npm install -g web-component-tester

    npm WARN engine launchpad@0.4.8: wanted: {"node":"^0.12"} (current: {"node":"4.0.0","npm":"3.3.3"})
    npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.0.0","npm":"3.3.3"})
    C:\Program Files (x86)\nodejs\wct-st -> C:\Program Files (x86)\nodejs\node_modules\web-component-tester\bin\wct-st
    C:\Program Files (x86)\nodejs\wct -> C:\Program Files (x86)\nodejs\node_modules\web-component-tester\bin\wct

    > bufferutil@1.1.0 install C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil
    > node-gyp rebuild

    C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      bufferutil.cc
    C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T>
        _NanEnsureLocal(v8::Local<T>
            )': function template has already been defined [C:\Program Files (x86)\nodejs\node_modules
            \web-component-tester\node_modules\bufferutil\build\bufferutil.vcxproj]
            C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(256): note: see declaration of
            '_NanEnsureLocal'
            C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(661): error C3083: 'smalloc': th
            e symbol to the left of a '::' must be a type [C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_mod
            ules\bufferutil\build\bufferutil.vcxproj]
            C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(661): error C2039: 'FreeCallback
            ': is not a member of 'node' [C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil\b
            uild\bufferutil.vcxproj]
            C:\Users\ant.ANTIX\.node-gyp\4.0.0\include\node\node_object_wrap.h(8): note: see declaration of 'node'
            C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(661): error C2061: syntax error:
            identifier 'FreeCallback' [C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil\bui
            ld\bufferutil.vcxproj]
            C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(665): error C2065: 'callback': u
            ndeclared identifier [C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil\build\buf
            ferutil.vcxproj]
            C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(665): error C2065: 'hint': undec
            lared identifier [C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil\build\bufferu
            til.vcxproj]
            C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(672): error C2665: 'node::Buffer
            ::New': none of the 4 overloads could convert all the argument types [C:\Program Files (x86)\nodejs\node_modules\web-co
            mponent-tester\node_modules\bufferutil\build\bufferutil.vcxproj]
            C:\Users\ant.ANTIX\.node-gyp\4.0.0\include\node\node_buffer.h(43): note: could be 'v8::MaybeLocal<v8::Object>
                node::B
                uffer::New(v8::Isolate *,char *,size_t)'
                C:\Users\ant.ANTIX\.node-gyp\4.0.0\include\node\node_buffer.h(31): note: or       'v8::MaybeLocal<v8::Object>
                    node::B
                    uffer::New(v8::Isolate *,v8::Local<v8::String>
                        ,node::encoding)'
                        C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(672): note: while trying to ma
                        tch the argument list '(v8::Isolate *, const char *, uint32_t)'
                        C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(676): error C2440: 'return': can
                        not convert from 'v8::MaybeLocal<v8::Object>
                            ' to 'v8::Local<v8::Object>
                                ' [C:\Program Files (x86)\nodejs\node_modules\we
                                b-component-tester\node_modules\bufferutil\build\bufferutil.vcxproj]
                                C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(676): note: No constructor cou
                                ld take the source type, or constructor overload resolution was ambiguous
                                C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(683): error C2039: 'Use': is not
                                a member of 'node::Buffer' [C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil\bu
                                ild\bufferutil.vcxproj]
                                C:\Users\ant.ANTIX\.node-gyp\4.0.0\include\node\node_buffer.h(8): note: see declaration of 'node::Buffer'
                                C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\nan\nan.h(683): error C3861: 'Use': identi
                                fier not found [C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil\build\bufferuti
                                l.vcxproj]
                                gyp ERR! build error
                                gyp ERR! stack Error: `msbuild` failed with exit code: 1
                                gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
                                gyp ERR! stack     at emitTwo (events.js:87:13)
                                gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
                                gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
                                gyp ERR! System Windows_NT 10.0.10240
                                gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
                                gyp ERR! cwd C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\bufferutil
                                gyp ERR! node -v v4.0.0
                                gyp ERR! node-gyp -v v3.0.1
                                gyp ERR! not ok
                                C:\Program Files (x86)\nodejs
                                └── (empty)

                                npm ERR! Windows_NT 10.0.10240
                                npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "web-component-tester"
                                npm ERR! node v4.0.0
                                npm ERR! npm  v3.3.3
                                npm ERR! code ELIFECYCLE

                                npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
                                npm ERR! Exit status 1
                                npm ERR!
                                npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
                                npm ERR! This is most likely a problem with the bufferutil package,
                                npm ERR! not with npm itself.
                                npm ERR! Tell the author that this fails on your system:
                                npm ERR!     node-gyp rebuild
                                npm ERR! You can get their info via:
                                npm ERR!     npm owner ls bufferutil
                                npm ERR! There is likely additional logging output above.

                                npm ERR! Please include the following file with any support request:
                                npm ERR!     C:\Program Files (x86)\nodejs\npm-debug.log
                                npm ERR! code 1

was happening on node 0.12.7 and npm 2.(something) too

**Comment by MrAntix** [comment]
Some progress

I have installed npm 3.3.3 and managed to install the web-component-tester module.

but now when I run wct I get

    C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\q\q.js:155
                    throw e;
                          ^
    TypeError: Cannot read property 'match' of undefined
        at Object.chrome (C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\wct-local\lib\browsers.js:114:35)
        at C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\wct-local\lib\browsers.js:89:68
        at C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\q\q.js:2027:17
        at runSingle (C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\q\q.js:137:13)
        at flush (C:\Program Files (x86)\nodejs\node_modules\web-component-tester\node_modules\q\q.js:125:13)
        at process._tickCallback (node.js:355:11)

To be sure I have also installed all the dependencies
mocha, chai, async, lodash (3.0), sinon, sinon-chai

I'll keep trying, but if anyone had any in sight that would be appreciated

**Comment by MrAntix** [comment]
ok, its working (well same as it does for the tests run on polymer github)

I don't know if its something I've done or some other dependency has changed or something (shrug)

here's what I did
1) remove globally installed web-component-tester - in windows this goes in the "Program Files" dir, which needs admin permissions to alter, and I think that why it doesn't work globally - that combined with when you run as admin local stuff goes in the admins profile and not your user profile., So things are not found or not permitted.
2) download the latest repo
3) make sure you have bower installed (globally* works for bower) or `npm install bower`
4) run `bower install`

Now you can run `wct`, you get failures for IE but assuming you have chrome, the test pass for that

To avoid confusion, I like to run the tests in a chrome browser window. For this you can use polyserve (install globally* works for me).

1) open a command window (shift right click on you folder in explorer and select "open command window here"
2) run `polyserve'
3) browse to the tests e.g. http://localhost:8080/components/gold-email-input/test/index.html

* General note on installing globally with windows, using the -g switch is not always successful, instead I open an Administrator prompt and cd to the node directory (for me C:\program files (x86)\nodejs), here I run the install without -g

I guarantee nout :) good luck

**Comment by baazoo** [comment]
I have the same problem @MrAntix. I upgraded my npm but it didn't help. There are two packages in PSK (browser-sync and web-component-tester) that result in rebuilding 'bufferutil' and 'utf-8-validator' which causes this bug.
Do you have any idea how I can fix this?
