### ISSUE TITLE
Unable to install wct on mac osx by following the docs

### ISSUE THREAD

**Issue by sebs** [Polymer/web-component-tester#220]
```
---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
to: /usr/local/lib/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/2.47.1-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.18/chromedriver_mac32.zip
to: /usr/local/lib/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.18-x64-chromedriver


-----
selenium-standalone installation finished
-----

> wct-sauce@1.6.6 postinstall /usr/local/lib/node_modules/web-component-tester/node_modules/wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 2.94MB
Unzipping sc-4.3.10-osx.zip
Removing sc-4.3.10-osx.zip
Sauce Connect downloaded correctly
Removing /usr/local/lib/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher/sc/sc-4.3.10-osx.zip
/usr/local/bin/wct -> /usr/local/lib/node_modules/web-component-tester/bin/wct
/usr/local/bin/wct-st -> /usr/local/lib/node_modules/web-component-tester/bin/wct-st

> web-component-tester@3.3.22 postinstall /usr/local/lib/node_modules/web-component-tester
> node scripts/postinstall.js

/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:56
				throw err;
				      ^
Error: EACCES, permission denied '/Users/sebs/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:500:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:352:15)
    at Object.create.all.get (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Some remarks: 

* The install obviously fails
* The sauchelabs code is always downloaded. The output in the console is NOT right. I have tried it. Multiple installs form a starbucks. It would be nice, considering the "Fallacys of Network Computing" you do not put any blob you find in the WCT or make sure stuff gets downlloaded ONCE:

**Comment by sebs** [comment]
npm: 2.9.1
node: 0.12.3
polymer: 1.0

**Comment by garlicnation** [comment]
What are the permissions on `/Users/sebs/.config`?

**Comment by sebs** [comment]
Checking that later.

**Comment by sebs** [comment]
yeah, chmod with -R on .config helped. Only my user could write. Probably this is just a  annoying FAQ?

**Comment by sebs** [comment]
Thanks for the hint!
