### ISSUE TITLE
Error with post-install script

### ISSUE THREAD

**Issue by ajjohnston** [Polymer/web-component-tester#231]
I get this error after the post-install script runs.

````
node scripts/postinstall.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'user-home'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/jenkins/workspace/Navigation/nav-build/node_modules/bower/node_modules/configstore/index.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

...

npm ERR! web-component-tester@3.3.26 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-component-tester@3.3.26 postinstall script 'node scripts/postinstall.js'.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.
````

**Comment by mjgreen145** [comment]
+1, I have started seeing this recently too.

**Comment by mjgreen145** [comment]
@ajjohnston Did you manage to resolve this? I've started seeing this happen for a different module called "mout" now. It preventing our CI build from running tests (and therefore making it fail).

**Comment by ajjohnston** [comment]
@mjgreen145 Yeah, turns out the problem was with a Jenkins plugin we were using to manage different Node.js versions across our build jobs. It seems the error stems from Bower being unable to find a user home directory.
