### ISSUE TITLE
WCT fails to run with selenium-standalone error

### ISSUE THREAD

**Issue by pkearney13** [Polymer/web-component-tester#237]
Hi there, I recently installed the web compontent tester with no errors, when I run the command "wct" in my terminal it shows this error, any help on fixing this would be great thanks.

hook: prepare
hook: prepare:selenium
hook done: prepare:selenium
Installing and starting Selenium server for local browsers
----------
selenium-standalone installation starting
----------
---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
to: C:\Users\pkearney\WebstormProjects\PolyPower\node_modules\selenium-standalone\.selenium\selenium-server\2.47.1-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.18/chromedriver_win32.zip
to: C:\Users\pkearney\WebstormProjects\PolyPower\node_modules\selenium-standalone\.selenium\chromedriver\2.18-x64-chromedriver
---
ie install:
from: http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.47.0.zip
to: C:\Users\pkearney\WebstormProjects\PolyPower\node_modules\selenium-standalone\.selenium\iedriver\2.47.0-x64-IEDriverServer.exe
C:\Users\pkearney\WebstormProjects\PolyPower\node_modules\selenium-standalone\lib\install.js:278
  if (str[0] === quoteChar && str[str.length - 1] === quoteChar) {
         ^

TypeError: Cannot read property '0' of undefined
    at unquote (C:\Users\pkearney\WebstormProjects\PolyPower\node_modules\selenium-standalone\lib\install.js:278:10)
    at Request.<anonymous> (C:\Users\pkearney\WebstormProjects\PolyPower\node_modules\selenium-standalone\lib\install.js:292:14)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (C:\Users\pkearney\WebstormProjects\PolyPower\node_modules\request\request.js:1255:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)

**Comment by justinfagnani** [comment]
@pkearney13 is this still an issue. Just check that it hasn't been fixed in some updates since the report.
