### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by albertolobrano** [Polymer/web-component-tester#244]
Os: Mac
npm:2.14.7
node:v4.2.2

-----
selenium-standalone installation finished
-----
/usr/local/bin/wct -> /usr/local/lib/node_modules/web-component-tester/bin/wct
/usr/local/bin/wct-st -> /usr/local/lib/node_modules/web-component-tester/bin/wct-st

> web-component-tester@3.4.0 postinstall /usr/local/lib/node_modules/web-component-tester
> node scripts/postinstall.js

/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:56
				throw err;
				^

Error: EACCES: permission denied, open '/Users/alberto/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:549:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "web-component-tester"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! web-component-tester@3.4.0 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-component-tester@3.4.0 postinstall script 'node scripts/postinstall.js'.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by mattppp** [comment]
+1

**Comment by kamte** [comment]
Same error, on npm 3.4.0 and node 5.1.0

**Comment by kamte** [comment]
On Linux, I found that changing the folder in which npm installs packages solved the issue:
https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npm-s-default-directory-to-another-directory
