### ISSUE TITLE
Fails to start Firefox

### ISSUE THREAD

**Issue by StephenTurley** [Polymer/web-component-tester#248]
Trying to run WCT against the seed-element example project and I get the following error.

I'm running Fedora 23 and Firefox 42.

stem info: host: 'UX305LA', ip: '192.168.10.115', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.6-301.fc23.x86_64', java.version: '1.8.0_65'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:125)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:58)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:175)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:202)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:164)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:130)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'UX305LA', ip: '192.168.10.115', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.6-301.fc23.x86_64', java.version: '1.8.0_65'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
	... 9 more
Caused by: org.openqa.selenium.UnsupportedCommandException: Bad request
Command duration or timeout: 270 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'UX305LA', ip: '192.168.10.115', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.6-301.fc23.x86_64', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:223)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:134)
	... 14 more

**Comment by robdodson** [comment]
Looks related to https://github.com/yeoman/generator-polymer/issues/253

**Comment by azakus** [comment]
Ugh, this is because java is bad at figuring out `localhost`.

This happened on my home machine as well, and a workaround is to make sure 'localhost' is first in `/etc/hosts`

## broken
```
127.0.0.1 localhost.localdomain localhost
```

## works
```
127.0.0.1 localhost localhost.localdomain.
```

**Comment by Remeic** [comment]
does not seem to work, in opensuse in host was already as the first entry "localhost" and did not present instead localhost.localhostdomain. I tried to add it, but the problem remains. I attach here my hosts file



127.0.0.1	localhost 

# special IPv6 addresses
::1             localhost ipv6-localhost ipv6-loopback

fe00::0         ipv6-localnet

ff00::0         ipv6-mcastprefix
ff02::1         ipv6-allnodes
ff02::2         ipv6-allrouters
ff02::3         ipv6-allhosts

**Comment by azakus** [comment]
Oh, please try with WCT 4, which uses selenium 2.48.2.

**Comment by Remeic** [comment]
@azakus I need to update generator-polymer or is there a specific passage? Thank you in advance

**Comment by robdodson** [comment]
@Remeic youll want to update this line in your package.json https://github.com/PolymerElements/polymer-starter-kit/blob/master/package.json#L33

**Comment by Remeic** [comment]
@robdodson sorry for delay .
Still not working , i return on fedora where the localhost and localhost.localdomain have inverted position , i set localhost as primary and after i update package.json . i start "gulp test:local" and problem see the same

**Comment by robdodson** [comment]
@Remeic after you updated the line in package.json did you delete `node_modules` and re-run `npm install`?

**Comment by Remeic** [comment]
@robdodson no , sorry i only run "npm install -g web-component-tester" , i mistake sorry again.
But now gulp test and gulp serve work , thanks for the immense patience and the help <3

**Comment by robdodson** [comment]
yay awesome!
