### ISSUE TITLE
npm install fails for web-component-tester on node 0.10

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/web-component-tester#270]
`npm install` fails on installing the dependency `test-fixture`:

```shell
npm ERR! Error: No compatible version found: test-fixture@'github:PolymerElements/test-fixture'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","1.0.0","1.0.1","1.0.2"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-68-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/npm-debug.log
npm ERR! not ok code 0
```

**Comment by TimvdLippe** [comment]
The `package.json` used is

```js
{
  "name": "planningtool",
  "private": true,
  "devDependencies": {
    "browser-sync": "^2.7.7",
    "del": "^2.0.2",
    "glob-all": "^3.0.1",
    "gulp": "^3.8.5",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-cache": "^0.4.0",
    "gulp-changed": "^1.0.0",
    "gulp-html-extract": "^0.1.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.2.1",
    "gulp-jscs": "^3.0.0",
    "gulp-jscs-stylish": "^1.1.2",
    "gulp-jshint": "^1.6.3",
    "gulp-latex": "^1.0.1",
    "gulp-load-plugins": "^1.1.0",
    "gulp-minify-css": "^1.2.1",
    "gulp-minify-html": "^1.0.2",
    "gulp-rename": "^1.2.0",
    "gulp-replace": "^0.5.4",
    "gulp-size": "^2.0.0",
    "gulp-style-modules": "^0.1.0",
    "gulp-uglify": "^1.2.0",
    "gulp-useref": "^2.1.0",
    "gulp-vulcanize": "^6.0.0",
    "jshint-stylish": "^2.0.0",
    "merge-stream": "^1.0.0",
    "proxy-middleware": "^0.14.0",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.0.2",
    "through2": "^2.0.0",
    "url": "^0.11.0",
    "vulcanize": ">= 1.4.2",
    "web-component-tester": "^4.0.0"
  },
  "scripts": {
    "test": "gulp test:local",
    "start": "gulp serve",
    "lint": "gulp lint"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
```

**Comment by ibek** [comment]
I have the same problem, so I installed version 3.4.2 instead - "sudo npm install -g web-component-tester@3.4.2" which works fine. It seems the issue is caused by new dependency https://github.com/Polymer/web-component-tester/commit/6d3b04f43a105e21ec11d42f4e6346260b14ecb5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R66

**Comment by deadlyfingers** [comment]
Thanks @ibek 3.4.2 installs ok. I tried version 4 to 4.1.0 but returns error: `"Unsupported URL Type: github:PolymerElements/test-fixture"`

**Comment by shawncplus** [comment]
Just tossing a +1 on this. npm version 1.4.28, node version 4.2.2

**Comment by azakus** [comment]
Node 0.10 isn't supported right now due to https://github.com/vvo/selenium-standalone/issues/156.

**Comment by TimvdLippe** [comment]
I can verify that upgrading Node to v4.0.0 solves this issue, so it would make this a node 0.10 specific issue.

**Comment by azakus** [comment]
I've merged #274, which fixes the narrow case of this issue, but wct will still not run in node 0.10, because of the issue in selenium-standalone.
In fact, multiple dependencies have "moved on" from node 0.10 by declaring `"engine": ">= 0.12"`, in their `package.json` files.

**Comment by TimvdLippe** [comment]
Shall I close this as a wontfix? My problem was solved by simply upgrading, so other users should be guided to upgrade too I think.

**Comment by shawncplus** [comment]
@TimvdLippe It was closed with this pr https://github.com/Polymer/web-component-tester/pull/274

**Comment by TimvdLippe** [comment]
Oh okay, I probably misunderstood the comment of @azakus.
