### ISSUE TITLE
Errro while launching WCT for certain components

### ISSUE THREAD

**Issue by aemonge** [Polymer/web-component-tester#276]
I've got a successfull `wct` call on one of my components, but i've got this output on other:

```bash
λ datamanagers-us → wct                                                           λ git feature/codeQuallityAll|✚2… →
module.js:328
    throw err;
    ^

Error: Cannot find module 'has-binary-data'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-component-tester/node_modules/socket.io/lib/socket.js:10:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by aemonge** [comment]
Updating web-component-tester fixed it
