### ISSUE TITLE
Gulp-Babel build fails due to "Use of const in strict mode"

### ISSUE THREAD

**Issue by dudabone** [Polymer/web-component-tester#332]
We are using gulp-babel to build and we are getting the following error since last week:

[INFO] [10:24:18] Requiring external module babel-register
[ERROR] node_modules\web-component-tester\runner\cli.js:11
[ERROR] const chalk = require('chalk');
[ERROR] ^^^^^
[ERROR] SyntaxError: Use of const in strict mode.
[ERROR]     at exports.runInThisContext (vm.js:73:16)
[ERROR]     at Module._compile (module.js:443:25)
[ERROR]     at Module._extensions..js (module.js:478:10)
[ERROR]     at Object.require.extensions.(anonymous function) [as .js] (node_modules\babel-register\lib\node.js:166:7)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)
[ERROR]     at Module.require (module.js:365:17)
[ERROR]     at require (module.js:384:17)
[ERROR]     at Object.<anonymous> (node_modules\web-component-tester\runner.js:11:11)
[ERROR]     at Module._compile (module.js:460:26)

Seems like cli.js was changed 12 days ago.

**Comment by justinfagnani** [comment]
What version of node are you using?

**Comment by gazal-k** [comment]
I had the same problem when I was building my project with node v0.12.0, not with node v5.0.0 though.

**Comment by u4yk** [comment]
I'm getting this issue as well.  Do we know which branch introduced this issue?

**Comment by gazal-k** [comment]
The problem occurs when using wct > 4.3.0 on older node versions. I don't know exactly which versions. Our CI server was using 0.12 and that's where we saw the error.

Solution:

- Upgrade node or
- Downgrade wct

**Comment by justinfagnani** [comment]
Apologies, our tools are moving to support the latest Node LTS and latest stable. This means Node 4 and 6 right now.

**Comment by u4yk** [comment]
We rolled back to WCT 4.2.2, and it seems to be working.  Thanks, guys.

**Comment by justinfagnani** [comment]
@u4yk our current plan is to only support the latest LTS and stable. If you're not able to upgrade node, you won't get any new features. It'd be great to have feedback here. Are there things blocking you from upgrading node to a somewhat recent version?

**Comment by dudabone** [comment]
@justinfagnani, we are also using node 0.12 and cannot upgrade it in the near future (we are working on it though...). In the meantime we have downgraded to wct 4.2.2

**Comment by u4yk** [comment]
@justinfagnani we're planning on upgrading node,  but since this was in production,  we would need a change request to upgrade.  Reverting to 4.2.2 is a good stopgap until we do upgrade.
