### ISSUE TITLE
Cannot "replace" more than one element at the same time 

### ISSUE THREAD

**Issue by akc42** [Polymer/web-component-tester#355]
I have an `my-app` element that contains a `my-session` element that tries to log someone on as soon as it loads. In order to prevent this happening during testing, I replace it with a fake one that does nothing except expose the same properties and methods.

`my-app` also has an `iron-media-query` to decide what to display in the header panel dependant on the width of the display.  In trying to test this, I additionally want to replace this element with a mock.

As soon as I call replace for a second time, I get this error.
```
  Attempted to wrap instanceTemplate which is already wrapped
    <unknown> at   checkWrappedMethod at /components/sinonjs/sinon.js:1326:0
    <unknown> at           wrapMethod at /components/sinonjs/sinon.js:1366:0
    <unknown> at                 stub at /components/sinonjs/sinon.js:3426:0
    <unknown> at            <unknown> at test-app.html:87:0
    <unknown> at           wrapMethod at /components/sinonjs/sinon.js:1385:0
    <unknown> at                 stub at /components/sinonjs/sinon.js:3426:0
    <unknown> at            <unknown> at test-app.html:76:0
```

**Comment by akc42** [comment]
I am not sure this is relevant, as I think it more about an interaction between an attempt to stub the element in the text fixture and to replace elements with it..  Having since found that stub is working on the element prototype and as far as I can make out isn't stubbing the function (importHref) because its in Polymer.Base, I am using sinon.stub directly on the instance and now CAN replace two separate elements at the same time.

```
  describe('<pas-app>', function() {
    this.timeout(0);
    var app, session;
    before(function() {
      stub('iron-ajax', {
        generateRequest: function() {
          //make a no op;
        }
      });
    });

    beforeEach(function() {
      window.performance && window.performance.clearMarks();
      window.performance && window.performance.clearMeasures();
      app=fixture('basic');
      replace('iron-media-query').with('test-media');
      replace('pas-session').with('test-session');
      session = app.$.session;
      session.user = {};
    });
...
    it('should user logon change', function(done) {
      sinon.stub(app,'importHref');
      expect(app.isLoggedOn).to.be.false;
      session.user = {name: 'LoggonOnUser', nopass: false};
      flush(function() {
        expect(app.isLoggedOn).to.be.true;
        done();
      });
    });
```
