### ISSUE TITLE
Stubbing fixture element appears to cause next fixture load to fail

### ISSUE THREAD

**Issue by akc42** [Polymer/web-component-tester#357]
I have a fixture something like this

```
<test-fixture id="basic">
  <template>
    <pas-app unresolved></pas-app>
  </template>
</test-fixture>
```
The unresolved attribute is removed by pas-app element in the attached callback.

Various aspects of it are instantiated, then items replaced then stubbing occurs in nested describe, beforeEach pairs. In particular a session element is replaced by a mock

```
      beforeEach(function(done) {
        app=fixture('basic');
        stub('iron-ajax', {
          generateRequest: function() {
            //make a noop;
          }
        });
        replace('pas-session').with('test-session');
        flush(done);
      });
```

At one point in my test sequence I am trying to check that it calls importHref to lazily load an element so I stub it like this

```
       it('should try and load pas-pages', function(done) {
          var called = false;
          stub('pas-app', {
            importHref: function(href,onload,onerror,async) {
              called = href;
            }
          });
          session.user = {name: 'LoggonOnUser'};
          flush(function() {
            expect(called.slice(-14)).to.equal('pas-pages.html'); 
            done();
          });

        });
```

This test passes, but if I now put a breakpoint on the next time I hit the beforeEach function above,  before I call fixture('basic') the dom shows a fixture with a completely empty document fragment, and after I have called fixture('basic'), the pas-app element is there but remains un-resolved and its template is not stamped out 

The test that I refer to above output some pretty heavy error messages to the console

```
Cannot read property 'parentNode' of undefined
                           Function.invoke at /bower_components/sinonjs/sinon.js:2621
  test-session.proxy [as instanceTemplate] (eval at createProxy at /bower_components/sinonjs/sinon.js:2526:17), <anonymous>:1
               test-session._stampTemplate at /bower_components/polymer/polymer-mini.html:25
                test-session._initFeatures at /bower_components/polymer/polymer.html:3914
              test-session.createdCallback at /bower_components/polymer/polymer-micro.html:190
                           Function.invoke at /bower_components/sinonjs/sinon.js:2621
  pas-app.proxy [as instanceTemplate] (eval at createProxy at /bower_components/sinonjs/sinon.js:2526:17), <anonymous>:1
                    pas-app._stampTemplate at /bower_components/polymer/polymer-mini.html:25
```

**Comment by akc42** [comment]
I refactored my tests so that I stub the top level element before calling replace. When I do that, all the indications are that replace hasn't done anything, although its not done so silently.  All that has happened is that some tests that passed when the replace did work, now act as though  the  replace hasn't happened.

I must say I am really puzzled by what replace is actually doing.  With chrome dev tools and breakpoints I am looking at the dom  after each step, including a call to replace, and I can't see any identifiable change with replace.  Certainly there is no reference to the test-element, all the dom shows is the original element.

Should I be calling replace just once, before I call fixture?

**Comment by akc42** [comment]
Now I understand how replace works (see #356) I think this is just a symptom of that misunderstanding
