### ISSUE TITLE
WCT v4.3.5 not available in npm

### ISSUE THREAD

**Issue by jmalonzo** [Polymer/web-component-tester#386]
Hi there!

Can we please publish v4.3.5 in npmjs as well?

TIA!

**Comment by gertcuykens** [comment]
Can you test master because I think 4.3.5 for npm its broken?

`npm i -D https://github.com/polymer/web-component-tester/tarball/master`

```
wct                                                                                                    
module.js:457                                                                                                                
    throw err;                                                                                                               
    ^                                                                                                                        
                                                                                                                             
Error: Cannot find module './runner/cli'                                                                                     
    at Function.Module._resolveFilename (module.js:455:15)                                                                   
    at Function.Module._load (module.js:403:25)                                                                              
    at Module.require (module.js:483:17)                                                                                     
    at require (internal/module.js:20:19)                                                                                    
    at Object.<anonymous> (/Users/gert/node_modules/web-component-tester/runner.js:11:11)                                    
    at Module._compile (module.js:556:32)                                                                                    
    at Object.Module._extensions..js (module.js:565:10)                                                                      
    at Module.load (module.js:473:32)                                                                                        
    at tryModuleLoad (module.js:432:12)                                                                                      
    at Function.Module._load (module.js:424:3)  
```
