### ISSUE TITLE
Errors on Safari 10

### ISSUE THREAD

**Issue by lukasoppermann** [Polymer/web-component-tester#411]
So I am getting the following error:

> Failed to connect to SafariDriver after 10064 ms
> Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
> System info: host: 'lukas-macbook-pro.local', ip: '10.1.1.16', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_102'
> Driver info: driver.version: SafariDriver
> safari 10.0              Tests failed: Until Selenium's SafariDriver supports Safari 6.2+, 7.1+, & 8.0+, you must
> manually install it. Follow the steps at:
> https://github.com/SeleniumHQ/selenium/wiki/SafariDriver#getting-started
> Test run ended in failure: 8 failed tests, Until Selenium's SafariDriver supports Safari 6.2+, 7.1+, & 8.0+, you must
> manually install it. Follow the steps at:
> https://github.com/SeleniumHQ/selenium/wiki/SafariDriver#getting-started
> 
> chrome 54 (0/0/8)                       safari 10.0 (error)
> 
> 
> Error: 8 failed tests, Until Selenium's SafariDriver supports Safari 6.2+, 7.1+, & 8.0+, you must
> manually install it. Follow the steps at:
> https://github.com/SeleniumHQ/selenium/wiki/SafariDriver#getting-started

However for Safari 10 which I have, there is not additional driver, according to selenium.

How can I fix this? I am on OSX 10.11.6

**Comment by lukeis** [comment]
the stacktrace shows using 2.53.1 of selenium, you need to use 3.0.0 of selenium

**Comment by lukasoppermann** [comment]
Hey @lukeis I think `selenium-standalone` is included somewhere in `wct` (looks like this in the `npm -g list`) so it would need to be updated in the repo, correct?

**Comment by lukeis** [comment]
I would assume so, yes.

**Comment by elmariofredo** [comment]
@lukeis @lukasoppermann I get same error with version '3.0.1' so it doesn't seems to help

this issue seems to be related https://github.com/SeleniumHQ/selenium/issues/3260

**Comment by elmariofredo** [comment]
Sorry my bad, my issue is solved simply by killing existing webdriver process.

**Comment by rafagarcia** [comment]
@elmariofredo killing existing webdriver process? Can you be more descriptive?

**Comment by mroien** [comment]
I have the same issue I'm on Selenium 3.0.1, El Capitan, Safari 10.0.3. I ran `killall webdriverd` and same issue even after a restart.

**Comment by elmariofredo** [comment]
@rafagarcia same as @mroien killall webdriverd but it worked for me. Maybe you are experiencing some other issue.

**Comment by mroien** [comment]
I ran the `killall webdriverd` and then Safari at least spins up but my test won't run I get the error
```
Error: Promise was rejected with the following reason: Error: Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'LEFTOUT', ip: 'LEFTOUT', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12602.4.8, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: B197BA6A-7BB2-4A4A-82CF-53BAF1B70C1A
```

**Comment by rictic** [comment]
Safari 10 has webdriver built in, but you need to enable it. From https://webkit.org/blog/6900/webdriver-support-in-safari-10/

> * Ensure that the Develop menu is available. It can be turned on by opening Safari preferences (*Safari > Preferences* in the menu bar), going to the *Advanced* tab, and ensuring that the *Show Develop menu in menu bar* checkbox is checked.
> * Enable Remote Automation in the Develop menu. This is toggled via *Develop > Allow Remote Automation* in the menu bar.
> * Authorize `safaridriver` to launch the `webdriverd` service which hosts the local web server. To permit this, run `/usr/bin/safaridriver` once manually and complete the authentication prompt.

**Comment by mroien** [comment]
I did that ( I think), I have the first two bullet points done, I go to `/usr/bin/safaridriver` and double click the safaridriver.exec file. And get this
```
/usr/bin/safaridriver ; exit;

~                                                                              
▶ /usr/bin/safaridriver ; exit;
Could not start server: must specify at least one configuration argument.

Usage: safaridriver [options]
	-h, --help                Prints out this usage information.
	-p, --port                Port number the driver should use. If the server
	                          is already running, the port cannot be changed.
	                          If port 0 is specified, a default port will be used.

[Process completed]
```
But I don't get a `authentication prompt` Then I run `launchctl list | grep webdriverd` and get `-	0	com.apple.webdriverd`

**Comment by mroien** [comment]
I had to roll back to selenium-standalone 2.53.1 and add the extension back to Safari and it works. Can anyone confirm they are running Safari 10.0.3 with Selenium 3.0.1.

**Comment by vaishnavidesai** [comment]
Is there any resolution for this safari 10 issue for selenium 3.3.1 ?

**Comment by ArpitJain10** [comment]
Still facing this issue with selenium 3.4.0 on EI Capitan 10.11.6 wth safari 10.0.1(installed manually on mac), getting below error:

org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:29897 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Arpits-MacBook-Pro.local', ip: '192.168.1.6', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_131'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:60)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:40)
	at com.nobroker.automation.core.NoBrokerTestMainBase.beforeMethod(NoBrokerTestMainBase.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:29897 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:139)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:87)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:343)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	... 34 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 49 more
