### ISSUE TITLE
Install failing in selenium standalone installation

### ISSUE THREAD

**Issue by bernardius** [Polymer/web-component-tester#418]
Running install on version 4.3.6 is giving me this error(Looks related to this [https://github.com/vvo/selenium-standalone/issues/207](https://github.com/vvo/selenium-standalone/issues/207)

Failed to download selenium and/or chromedriver: Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-mac.tar.gz: 
    at Request.<anonymous> (/Users/chris.bernard/infusionsoft/infusionsoft-core/node_modules/selenium-standalone/lib/install.js:392:17)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/Users/chris.bernard/infusionsoft/infusionsoft-core/node_modules/selenium-standalone/node_modules/request/request.js:1255:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at TLSSocket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
selenium-standalone will attempt to re-download next time it is run.

**Comment by maxknee** [comment]
@bernardius please see https://github.com/Polymer/wct-local/pull/45
