### ISSUE TITLE
Cannot contribute to repo on Windows machines due to test assertion paths

### ISSUE THREAD

**Issue by owendismuke** [Polymer/web-component-tester#499]
When troubleshooting #498, I ran into the issue that some internal test assertions are looking for a *nix path (`../{dir}/`) which prevents users on a Windows machine from getting a successful prepublish.

``` 
1) paths .expand expands directories into their files:
     AssertionError: expected [ 'foo\\one.js', 'foo\\two.html' ] to have the same members as [ 'foo/one.js', 'foo/two.html' ]
      at test\unit\paths.js:32:47
      at next (native)
      at fulfilled (test\unit\paths.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  2) paths .expand expands directories into index.html when present:
     AssertionError: expected [ 'bar\\index.html' ] to have the same members as [ 'bar/index.html' ]
      at test\unit\paths.js:32:47
      at next (native)
      at fulfilled (test\unit\paths.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by rictic** [comment]
Arg, sorry about that. Should use `path.sep` or `path.join()`. Happy to accept a PR, otherwise we'll get to this after Polymer 2.0 is out
