### ISSUE TITLE
Suite `title` should be a "string" but "undefined" was given instead

### ISSUE THREAD

**Issue by idoshamun** [Polymer/web-component-tester#532]
I am encountering this error message randomly in my Jenkins output logs:
`Tests failed: Error thrown outside of test function: Suite `title` should be a "string" but "undefined" was given instead.`

Most the time just rerunning the job fixes the issue but I want to fix it completely.
I don't know how to reproduce as it happens randomly.

Versions:
polymer 2.0.0-rc.5
wct 5.0.1
polymer-cli 0.18.0

**Comment by cadwmaster** [comment]
Have the same problem, found out `wct` is looking in all the directories of the component and if finds another html file before that's the one executed, and if that file doesn't have a suite command then you'll get that error.

**Comment by Bubbit** [comment]
I'm experiencing the same issue, haven't done a deep dive yet like cadwmaster, but I'm experiencing it while using selenium, so not just browser-stack (also with wct 6.0.0)

**Comment by imthinhvu** [comment]
Also experiencing this issue...

Noticing that we are getting this error when running more than 48 tests, but less will give us a success. 

Versions:
polymer 1.2.3
wct 5.0.1

**Comment by motss** [comment]
Not sure if this log is helpful. This thing is so annoying and no way to figure out why it happened! 😢 

```sh
Error: Error thrown outside of test function: Suite `title` should be a "string" but "undefined" was given instead.
, Timed out
error:   cli runtime exception: Error: Error thrown outside of test function: Suite `title` should be a "string" but "undefined" was given instead.
, Timed out
error:   Error: Error thrown outside of test function: Suite `title` should be a "string" but "undefined" was given instead.
, Timed out
    at /home/travis/.nvm/versions/node/v7.10.0/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:170:27
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/.nvm/versions/node/v7.10.0/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by Bubbit** [comment]
Not sure if other people are experiencing the same, but it always seems to happen on a certain test. I still haven't dived into which test precisely as there are 500+ tests in the repo. So before I do can someone confirm or deny this?

**Comment by emilbillberg** [comment]
I upgraded from v5.0.1 to v6.0.0 and are now experiencing the same issue. Just like Cadwmaster said it is when you have another html file in the same folder as your test file you get this error. I like to keep my test in the same folder as the component I'm testing. Any progress on this issue?

**Comment by kaspnilsson** [comment]
We on the PolyGerrit team are dealing with this issue too.

**Comment by notwaldorf** [comment]
@justinfagnani 👀

**Comment by beckysiegel** [comment]
It seems at least *part* of our (PolyGerrit's) problem was having incorrect bower paths in some of our test files. Why these passed before (and sometimes intermittently) I'm not sure. Something happened and they went from intermittently passing to failing 100% of the time. Updating the bower component path seems to get us passing again (we'll see if intermittent or not shortly!)

**Comment by justinfagnani** [comment]
Does anyone have a github repo that experiences this problem? Even if it is an import pats problem, I'd like to find why the error message is so cryptic.

**Comment by beckysiegel** [comment]
@justinfagnani not github, but this is the CL that fixed our CI (at least for now) https://gerrit-review.googlesource.com/c/107733/

**Comment by beckysiegel** [comment]
If you clone the repo and check out the commit prior to it, it's should be reproducible . 
git clone https://gerrit.googlesource.com/gerrit

**Comment by emilbillberg** [comment]
After looking in to the issue I found that my paths to `web-component-tester/browser.js` was wrong and that is what caused the error. I encourage everyone with this issue to take an extra look at all the paths to your elements.

**Comment by sp1rs** [comment]
Is anyone still facing this issue?

**Comment by bennypowers** [comment]
yeah I've got it. wrong paths doesn't seem to be the issue

**Comment by ageblade** [comment]
After two days of trial and error I managed to solve this problem by removing a reference to `iron-resizable-behavior` on my element source code (not even the test file). Maybe this will help someone along the way... 😪

**Comment by itaiterner** [comment]
For me it's fails after calling an HTML attribute with the following convention: `this.$['some-id']`.
After changing it to `this.$.someId` using camel case convention, it's works.

**Comment by visionscaper** [comment]
I found out that I got this error because some test files loaded with `loadSuites` did not exist any more.

**Comment by justinfagnani** [comment]
We have some changes to path resolution coming up that might fix some of the hard-to-track-down errors like this one. I'm not sure `this.$` would interact here, that one's interesting. @visionscaper seems like `loadSuites` needs some better error handling.

**Comment by visionscaper** [comment]
@justinfagnani that sounds like a good plan, thanks.

**Comment by xscheiner** [comment]
We have also had this issue and I just spent the better part of 2 days tracking down the source on a single component that has about 150 tests. We run that in Browserstack against Edge, IE11 and Chrome. The tests consistently passed running IE and Edge in Browserstack and Chrome locally, but every time we ran them in Chrome on Browserstack, we got this error.

The component is fairly large and has two main elements that consume some combination of 5 sub-element that they import. The error happened on one single sub-element when it was imported into the larger of the two main elements.

In addition, we have another component we call js-imports that we use to import third party libraries. One page in that imports ramdajs which we use. This is the entire source of the ramda.html page:

`<script src="./js/ramda.min.js"></script>`

That was being imported in both the main element and the sub-element that the main element imported. When I removed the ramda.html import from the sub-element, the problem went away.

Now we also have a page in js-imports that for moment js and that was also used in both elements and there was and is no issue. The difference is that the moment one imports moment from bower_components rather than from a folder inside itself as the ramda one does. That appears to be the issue.

This is a damn painful bug to track down but I think given it only affects html imports (which are being deprecated) and happens in Polymer 1, I'd be surprised if there were a fix, if one is even possible. I'm only posting here to help people with their own issues if this arises.

Unfortunately, the only hope is to do more or less what I did: keep commenting out huge amounts of code and slowly narrowing till you find the offending line.
