### ISSUE TITLE
No browsers configured to run Error

### ISSUE THREAD

**Issue by hyyan** [Polymer/web-component-tester#634]
**Description**

I am trying to run web components tests using WCT on Linux machine we use to handle building and testing our projects.
But I am always getting the same error when I run `wct`  or `polymer test` commands which is `No browsers configured to run`
```
-bash-4.2$ wct

Error: No browsers configured to run
```
I have tried to declare the local browser I want to use 

```
-bash-4.2$ polymer test -l firefox

Error: The following browsers were not found: firefox. (All installed browsers found: )

error:   cli runtime exception: Error: The following browsers were not found: firefox. (All installed browsers found: )
error:   Error: The following browsers were not found: firefox. (All installed browsers found: )
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/wct-local/lib/browsers.js:63:19)
    at next (native)
    at fulfilled (/usr/lib/node_modules/polymer-cli/node_modules/wct-local/lib/browsers.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I have also tried the following with polymer cli but no luck

`DEBUG=launchpad:* polymer test`
`DEBUG=launchpad:* polymer test --local firefox`

**Versions & Environment**

Polymer CLI: 1.5.4
WCT: 6.3.0
node: 6.6.0
Operating System: Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hyyan** [comment]
The problem can be solved by setting the following environment vars 

```
LAUNCHPAD_FIREFOX=/usr/local/bin/firefox
LAUNCHPAD_CHROME=/usr/bin/chromium-browser
```
