### ISSUE TITLE
Possible issue with latest wct-sauce 2.0.0 + wct 6.4.2 rollout

### ISSUE THREAD

**Issue by usergenic** [Polymer/web-component-tester#664]
Per @bicknellr 

hola, i'm running into an issue trying to `polymer test --sauce default`:

```
Creating Sauce Connect tunnel
Sauce Connect log: /tmp/***/sc.log
Sauce tunnel active: ***
error:   Uncaught exception: TypeError: Cannot read property 'value' of undefined
error:   TypeError: Cannot read property 'value' of undefined                 
    at /usr/local/google/home/bicknellr/.nvm/versions/node/v9.4.0/lib/node_modules/polymer-cli/node_modules/wd/lib/webdriver.js:134:85            Linux chrome ()                       
    at Request._callback (/usr/local/google/home/bicknellr/.nvm/versions/node/v9.4.0/lib/node_modules/polymer-cli/node_modules/wd/lib/http-utils.js:88:7)
    at Request.self.callback (/usr/local/google/home/bicknellr/.nvm/versions/node/v9.4.0/lib/node_modules/polymer-cli/node_modules/wd/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/usr/local/google/home/bicknellr/.nvm/versions/node/v9.4.0/lib/node_modules/polymer-cli/node_modules/wd/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/usr/local/google/home/bicknellr/.nvm/versions/node/v9.4.0/lib/node_modules/polymer-cli/node_modules/wd/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
```

**Comment by usergenic** [comment]
For those playing at home, this is the useless error you get when Sauce says "Uh oh, you're out of minutes!" because of an account issue.

That's some terrible UX.
