### ISSUE TITLE
WCT hangs on bdd only

### ISSUE THREAD

**Issue by dman777** [Polymer/web-component-tester#680]
I am not having any issues with tdd interfaces, but only when bdd is used wct hangs. Both I run on a headless server with xvfb-run:

Skeleton test:
```html

<body>

    <!-- You can use the document as a place to set up your fixtures. -->
    <test-fixture id="sp-veteran">
      <template>
          <sp-veteran></sp-veteran>
      </template>
    </test-fixture>

    <script>
      describe('sp-veteran', function() {
        let myEl;

          myEl = fixture('sp-veteran');

        it('should foo', () => {
          foo = true;
          expect(foo).to.be.true;
        });

      }); <!--end of root describe -->
   </script>

  </body>
```
```
one@work:~/github/client$ xvfb-run polymer test
Installing and starting Selenium server for local browsers
Selenium server running on port 42988
chrome 64                Beginning tests via http://localhost:8081/components/sp6/generated-index.html?cli_browser_id=0
chrome failed to maximize
chrome 64                ✖ sp-veteran/sp-veteran.html?dom=shady

  Timed out loading http://localhost:8081/components/sp6/test/sp-veteran/sp-veteran.html?dom=shady
    <unknown> at                       done at /components/mocha/mocha.js:1638:0
    <unknown> at         Runner.<anonymous> at /components/mocha/mocha.js:5311:0
    <unknown> at   Runner.EventEmitter.emit at /components/mocha/mocha.js:363:0
    <unknown> at                  <unknown> at /components/mocha/mocha.js:5298:0
    <unknown> at            Runner.runSuite at /components/mocha/mocha.js:5096:0

chrome 64                Tests failed: 1 failed tests
Test run ended in failure: 1 failed tests

chrome 64 (0/0/1)


Error: 1 failed tests

error:   cli runtime exception: Error: 1 failed tests
error:   Error: 1 failed tests
    at /home/one/n/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:170:27
    at Generator.next (<anonymous>)
    at fulfilled (/home/one/n/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

```
Using Polymer 1.*

one@work:~/github/client$ polymer test --version
1.6.0
one@work:~/github/client$ node -v
v9.4.0
```

**Comment by dman777** [comment]
Please disregard, this was an error on a import filename that was changed from search and replace
