### ISSUE TITLE
Node 10: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by pdesjardins90** [Polymer/web-component-tester#717]
After upgrading node, WCT doesn't work anymore. The error is: 
`TypeError: Cannot read property '1' of null`

Node v10.0.0
WCT version: 6.5

Steps to reproduce:
- polymer init (shop app)
- polymer test

Stack trace:

```
cli runtime exception: TypeError: Cannot read property '1' of null
error:   TypeError: Cannot read property '1' of null
    at module.exports (/Users/x/.config/yarn/global/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:61:29)
    at processExports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:82:25)
    at module.exports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:164:10)
    at /Users/x/.config/yarn/global/node_modules/web-component-tester/runner/paths.js:49:23
    at Generator.next (<anonymous>)
    at /Users/x/.config/yarn/global/node_modules/web-component-tester/runner/paths.js:20:71
    at new Promise (<anonymous>)
```

**Comment by web-padawan** [comment]
See Polymer/tools#280

**Comment by t1djani** [comment]
Same for me.

**Comment by jrpool** [comment]
Likewise.

**Comment by akc42** [comment]
I think its this problem.  I went through with the debugger and it failed when trying to promisfy `glob`
https://github.com/nodegit/promisify-node/issues/28

**Comment by luckyincode** [comment]
Got this too.  Had to switch travis ci to use 9 for now.

**Comment by paladox** [comment]
There's a new release for promisify-node which fixes support for nodejs 10 https://github.com/nodegit/promisify-node/commits/master

**Comment by paladox** [comment]
This was fixed in https://github.com/Polymer/tools/commit/29a85f97d066da538cb26b85278181a7dfb85b80 as the repo was moved to there.

**Comment by pdesjardins90** [comment]
I can confirmed this is fixed and released, thanks guys!

**Comment by usergenic** [comment]
(FWIW this was fixed by using node's own promisify and dropping support for Node < 8)
